#数据表配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wuliancan
    url: jdbc:mysql://127.0.0.1:3306/rwlmall?useSSL=false&characterEncoding=utf-8
  #spring:
  #  datasource:
  #      url: jdbc:jtds:sqlserver://rm-bp1d1t1do2ty7m1o1do.sqlserver.rds.aliyuncs.com:3433;DatabaseName=rwlmall
  #      username: mhk_qc
  #      password: mhk_qc_1
  #      driver-class-name: net.sourceforge.jtds.jdbc.Driver
  #      hikari:
  #        connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379



#服务器配置
server:
  port: 8008

#微信配置
wechat:
  appId: wx6facec47c2fca33b
  appSecret: d889f98ca71b67d8cb821be34a91c98
#  mchId: 10024153
#  mchKey: braggadocio345l6ackadaisicalness
#  keyPath: /home/wcp/rwlmall/src/main/resources/static/h5.p12
#  notifyUrl:  https://rtest.rwlai.com/rwlmall/pay/notify


#微信认证url配置
redirecturl:  http://www.embracex.com/rwlmall/wechat/userinfo
authurl:  http://www.embracex.com/rwlmall/wechat/login


## yml配置日志输出的格式以及日志文件
#logging:
#  file: T:\Java\log\rwlmall\rwlmall.log
#  path: T:\Java\log\rwlmall
#  pattern:
## %d = 日期  %msg = 消息  %n = 换行    只是修改控制台输出格式
#  console: "%d - %msg%n"


#图片路径配置
qiniuimageurl: https://image.rwlai.com/
imagepath: /home/wcp/images/
imageurl: https://rtest.rwlai.com/rwlmall/images/
excelpath: /home/wcp/excel/

#云测Testin短信服务
account: rangwolai
password: Rangwolai1
sendurl: http://118.178.189.133/msg/
